type: ASTAR              # ASTAR | DIJKSTRA | MPPI
grid:
  resolution: 0.2
  limits: {x: [-5,5], y: [-5,5], z: [-5,5]}
interpolation: "Quintic"
obstacle_inflation_ratio: 1.5

# astar:
#   heuristic: euclidean  TODO: Check for any other useful heuristics